export { default as Footer } from "./footer/Footer"
export { default as Category } from "./category/Category"
export { default as Header } from "./header/Header"
export { default as Logo } from "./logo/Logo"
export { default as Selling } from "./selling/Selling"
export { default as Steps } from "./steps/Steps"
export { default as Subscribe } from "./subscribe/Subscribe"
export { default as Testimonials } from "./testimonials/Testimonials"